#pragma once

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.6.0
// Descriptor size: 60 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                19 |
// +----------+-------+-------------------+
static const uint8_t hidReportDescriptor[] = 
{
    0x05, 0x01,          // UsagePage(Generic Desktop[0x0001])
    0x09, 0x05,          // UsageId(Gamepad[0x0005])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x01,          //     ReportId(1)
    0x09, 0x01,          //     UsageId(Pointer[0x0001])
    0xA1, 0x00,          //     Collection(Physical)
    0x05, 0x09,          //         UsagePage(Button[0x0009])
    0x19, 0x01,          //         UsageIdMin(Button 1[0x0001])
    0x29, 0x18,          //         UsageIdMax(Button 24[0x0018])
    0x15, 0x00,          //         LogicalMinimum(0)
    0x25, 0x01,          //         LogicalMaximum(1)
    0x95, 0x18,          //         ReportCount(24)
    0x75, 0x01,          //         ReportSize(1)
    0x81, 0x02,          //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x01,          //         UsagePage(Generic Desktop[0x0001])
    0x09, 0x30,          //         UsageId(X[0x0030])
    0x09, 0x31,          //         UsageId(Y[0x0031])
    0x09, 0x32,          //         UsageId(Z[0x0032])
    0x09, 0x33,          //         UsageId(Rx[0x0033])
    0x09, 0x34,          //         UsageId(Ry[0x0034])
    0x09, 0x35,          //         UsageId(Rz[0x0035])
    0x09, 0x36,          //         UsageId(Slider[0x0036])
    0x09, 0x37,          //         UsageId(Dial[0x0037])
    0x16, 0x00, 0x80,    //         LogicalMinimum(-32,768)
    0x26, 0xFF, 0x7F,    //         LogicalMaximum(32,767)
    0x95, 0x08,          //         ReportCount(8)
    0x75, 0x10,          //         ReportSize(16)
    0x81, 0x02,          //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                //     EndCollection()
    0xC0,                // EndCollection()
};

#pragma pack(push,1)

#define HID_REPORT_INPUT1_ID (1)
struct HidReportInput1
{
    uint8_t ReportId = HID_REPORT_INPUT1_ID;
    uint8_t Payload[19];
};

#pragma pack(pop)